### ISSUE TITLE
User Story - Create tree REST services using NodeJS [M]

### ISSUE THREAD

**Issue by albertodelazzari** [larusba/izs#12]
List of services:

- full text search #9 
- single shortest path #10 
- muti shortest path #11 

For service 2 and 3:

return not only a 200 HTTP code if a path exists but also a JSON payload (with a boolean value).

For service 1:

return not a JSON payload representing all the paths

[Node JS Docker App](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/)

**Comment by agarofalo-larus** [comment]
https://www.ru-rocker.com/2018/08/28/how-to-make-a-simple-crud-example-using-expressjs-and-neo4j/
